Repository paritytech/substrate-api-sidecar, pull requests merged in 2020-06, with the labels that each got.

#66 Add wasm-pack install instructions to README.md
  README.md
Labels: documentation

#73 Add doc comments to main
  src/main.ts
Labels: documentation

#105 Update API to support dry_run
  package.json
  src/ApiHandler.ts
  yarn.lock
Labels: A2 - Insubstantial, B0 - Silent

#122 Improve type specificity of `get` & `post` params
  package.json
  src/main.ts
  yarn.lock
Labels: B0 - Silent

#129 Create a file to gather all config requirements and update README
  .env-sample
  .env.parity
  README.md
  specs.yml
  src/config_setup.ts
  src/main.ts
  yarn.lock
Labels: I8 - Enhancement
