Repository paritytech/substrate-api-sidecar, pull requests merged in 2021-01, with the labels that each got.

#372 refactor: Optimize `accounts/{accountId}/staking-payouts` blocking query complexity
  package.json
  src/services/accounts/AccountsStakingPayoutsService.ts
  yarn.lock
Labels: I7 - Optimization :bicyclist:

#390 fix: Increase node.js stack size in order to decode election solutioins
  package.json
Labels: B3 - API Noteworthy

#391 fix: Use correct registry when creating calls; Remove usage of derive.chain.getBlock
  package.json
  src/services/blocks/BlocksService.spec.ts
  src/services/blocks/BlocksService.ts
  yarn.lock
Labels: P2 - ASAP

#388 fix: Update fee calc to use `system::constants::BlockWeights.per_class.normal.base_extrinsic`
  src/services/blocks/BlocksService.ts
  src/services/test-helpers/mock/mockApi.ts
Labels: B3 - API Noteworthy, I2 - Bug 🐜, P2 - ASAP

#399 feat!: Type definition specification with env vars and JSON files
  README.md
  config/errors-en.json
  config/types.json
  package.json
  src/SidecarConfig.ts
  src/Specs.ts
  src/main.ts
  src/types/sidecar-config/CONFIG.ts
  src/types/sidecar-config/SidecarConfig.ts
  yarn.lock
Labels: B2 - Breaks API

#386 feat: Add finalized tag when querying blocks (Tests included)
  docs/src/openapi-v1.yaml
  src/controllers/blocks/BlocksController.ts
  src/services/blocks/BlocksService.spec.ts
  src/services/blocks/BlocksService.ts
  src/services/test-helpers/mock/data/blocks789629Fork.json
  src/services/test-helpers/mock/mockBlock789629.ts
  src/services/test-helpers/responses/blocks/blocks789629.json
  src/types/responses/Block.ts
Labels: B3 - API Noteworthy
