Repository paritytech/substrate-api-sidecar, pull requests merged in 2022-09, with the labels that each got.

#1010 docs: remove fee integration guide
  README.md
  guides/CHAIN_FEE_INTEGRATION.md
Labels: I5 - Documentation :book:

#1023 feat: validateBooleanMiddleware for controllers
  src/controllers/accounts/AccountsBalanceInfoController.ts
  src/controllers/accounts/AccountsStakingPayoutsController.ts
  src/controllers/blocks/BlocksController.ts
  src/controllers/blocks/BlocksTraceController.ts
  src/controllers/node/NodeTransactionPoolController.ts
  src/controllers/pallets/PalletsStorageController.ts
  src/controllers/paras/ParasController.ts
  src/controllers/transaction/TransactionMaterialController.ts
  src/middleware/validate/index.ts
  src/middleware/validate/util.ts
  src/middleware/validate/validateAddressMiddleware.spec.ts
  src/middleware/validate/validateBooleanMiddleware.spec.ts
  src/middleware/validate/validateBooleanMiddleware.ts
Labels: I8 - Enhancement

#1059 chore(deps): updated polkadot-js deps
  package.json
  yarn.lock
Labels: dependencies
