Repository paritytech/substrate-api-sidecar, pull requests merged in 2023-01, with the labels that each got.

#1166 feat: add `/paras/head/included-candidates` and `/paras/head/backed-candidates`
  docs/dist/app.bundle.js
  docs/src/openapi-v1.yaml
  e2e-tests/latest/endpoints/polkadot.ts
  src/controllers/paras/ParasController.ts
  src/services/paras/ParasService.spec.ts
  src/services/paras/ParasService.ts
  src/services/test-helpers/mock/paras/eventsHex.ts
  src/services/test-helpers/responses/paras/parasHeadBackedCandidates.json
  src/services/test-helpers/responses/paras/parasHeadIncludedCandidates.json
  src/types/responses/Paras.ts
Labels: A0 - Please Review, I8 - Enhancement, C1 - Parachain, C0 - Relay

#1095 feat: add nomination pools support
  docs/dist/app.bundle.js
  docs/src/openapi-v1.yaml
  e2e-tests/latest/endpoints/polkadot.ts
  src/chains-config/kusamaControllers.ts
  src/chains-config/polkadotControllers.ts
  src/chains-config/westendControllers.ts
  src/controllers/index.ts
  src/controllers/pallets/PalletsNominationPoolsController.ts
  src/controllers/pallets/index.ts
  src/services/pallets/PalletsNominationPoolsService.spec.ts
  src/services/pallets/PalletsNominationPoolsService.ts
  src/services/pallets/index.ts
  src/services/test-helpers/mock/data/mockNonimationPoolResponseData.ts
  src/services/test-helpers/mock/mockApi.ts
  src/types/responses/PalletNominationPools.ts
  src/types/responses/index.ts
Labels: A0 - Please Review

#1206 chore(deps): update polkadot-js deps
  package.json
  src/services/blocks/BlocksService.ts
  src/services/node/NodeTransactionPoolService.ts
  src/services/transaction/TransactionFeeEstimateService.ts
  yarn.lock
Labels: A0 - Please Review, D0 - Dependencies
